# FROM nvidia/cuda:11.3.0-runtime-ubuntu20.04
# FROM nvidia/cuda:11.1-runtime-ubuntu20.04
# FROM nvidia/cuda:10.2-runtime-ubuntu18.04
# FROM nvidia/cudagl:10.2-runtime-ubuntu18.04
FROM nvidia/cudagl:10.2-devel-ubuntu18.04
# FROM nvidia/cudagl:11.4.0-runtime-ubuntu18.04

# Copyright (c) 2020, NVIDIA CORPORATION. All rights reserved.
# Full license terms provided in LICENSE.md file.
# To build:
# docker build -t nvidia-dope:noetic-v1 -f Dockerfile.noetic ..

ENV HOME /root
ENV DEBIAN_FRONTEND=noninteractive


RUN sed -i s:/archive.ubuntu.com:/free.nchc.org.tw/ubuntu:g /etc/apt/sources.list
RUN apt-get -y update
# install ros

RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu bionic main" > /etc/apt/sources.list.d/ros-latest.list'
RUN apt-get install -y apt-utils curl
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -
# RUN apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
RUN apt-get -y update
RUN cat /etc/apt/sources.list
RUN apt-get install -y ros-melodic-desktop-full
RUN echo "source /opt/ros/melodic/setup.bash" >> ~/.bashrc
RUN apt-get install -y python-rosdep \
    python-rosinstall \
    python-rosinstall-generator \
    python-wstool \
    python-setuptools \
    python-pip \
    build-essential \
    ros-melodic-control-msgs \
    ros-melodic-moveit-msgs \
    libglm-dev \
    libglew-dev
    # ros-melodic-openni-camera

# Install system and development components
RUN apt-get update && apt-get -y --no-install-recommends install \
    wget \
    xz-utils \
    python3.6-tk \
    git \
    cmake \
	build-essential \
	gnupg2 \
	lsb-release \
    && apt-get -y autoremove \
    && apt-get clean

# install pip
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
RUN python3 get-pip.py
# pip install required Python packages
# RUN pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
# RUN pip3 install torch==1.6.0 torchvision==0.7.0
# RUN pip3 install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html
# COPY requirements.txt ${HOME}
# RUN python3 -m pip install --no-cache-dir -r ${HOME}/requirements.txt
# RUN rm ${HOME}/requirements.txt

# Setup catkin workspace
ENV CATKIN_WS ${HOME}/catkin_ws
COPY . ${CATKIN_WS}/src/

ENV TERM=xterm
